name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Defining variables
        run: echo "Defining variables"
        env:
            MYVAR: hola
            MYVAR2: 234
      - name: New step
        run: echo $MYVAR $MYVAR2
