name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Defining variables
        run: |
            echo "MYVAR=${{ 2 }}" >> $GITHUB_ENV
            echo "MYVAR2=kkkk" >> $GITHUB_ENV
      - name: New step
        run: echo $MYVAR $MYVAR2 $GITHUB_ACTOR
    #   - name: make the script executable
    #     run: chmod +x ./script01.sh
      - name: run a script
        run: bash ./script01.sh
        env:
            otravar: Milo